version: '1.0'
steps:
  BuildingDockerImage:
    title: Building Docker Image
    type: build
    image_name: ceruleanlabs/smashbot
    working_directory: ./
    tag: '${{CF_BRANCH_TAG_NORMALIZED}}'
    dockerfile: Dockerfile
    build_arguments:
      - SONAR_TOKEN=${{SONAR_TOKEN}}
      - GIT_BRANCH=${{CF_BRANCH}}

