version: '1.0'
steps:
  BuildingDockerImage:
    title: Building Docker Image
    type: build
    image_name: ceruleanlabs/smashbot
    working_directory: ./
    tag: '${{CF_BRANCH_TAG_NORMALIZED}}'
    dockerfile: Dockerfile
    build_arguments:
      - SONAR_PROJECT=${{SONAR_PROJECT}}
      - SONAR_ORG=${{SONAR_ORG}}
      - SONAR_HOST=${{SONAR_HOST}}
      - SONAR_TOKEN=${{SONAR_TOKEN}}

