version: '1.0'
steps:
  BuildingDockerImage:
    title: Building Docker Image
    type: build
    image_name: ceruleanlabs/smashbot
    working_directory: ./
    tag: '${{CF_BRANCH_TAG_NORMALIZED}}'
    dockerfile: Dockerfile
    build_arguments:
      - PR_BASE=${{CF_PULL_REQUEST_TARGET}}
      - PR_BRANCH=${{CF_BRANCH}}
      - PR_ID=${{CF_PULL_REQUEST_ID}}
      - SONAR_TOKEN=${{SONAR_TOKEN}}

